[package]
name = "ch12"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "waiter"
path = "bin/wait.rs"

[[bin]]
name = "killer"
path = "bin/kill.rs"

[lib]
name = "signals"
path = "src/lib.rs"

[dependencies]
libc = "0.2"
